// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_INCLUDED_test_2eproto
#define PROTOBUF_INCLUDED_test_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_2eproto 

namespace protobuf_test_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_2eproto
namespace GrpcService {
class MyRequest;
class MyRequestDefaultTypeInternal;
extern MyRequestDefaultTypeInternal _MyRequest_default_instance_;
class MyResponse;
class MyResponseDefaultTypeInternal;
extern MyResponseDefaultTypeInternal _MyResponse_default_instance_;
}  // namespace GrpcService
namespace google {
namespace protobuf {
template<> ::GrpcService::MyRequest* Arena::CreateMaybeMessage<::GrpcService::MyRequest>(Arena*);
template<> ::GrpcService::MyResponse* Arena::CreateMaybeMessage<::GrpcService::MyResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace GrpcService {

// ===================================================================

class MyRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GrpcService.MyRequest) */ {
 public:
  MyRequest();
  virtual ~MyRequest();

  MyRequest(const MyRequest& from);

  inline MyRequest& operator=(const MyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MyRequest(MyRequest&& from) noexcept
    : MyRequest() {
    *this = ::std::move(from);
  }

  inline MyRequest& operator=(MyRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MyRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MyRequest* internal_default_instance() {
    return reinterpret_cast<const MyRequest*>(
               &_MyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MyRequest* other);
  friend void swap(MyRequest& a, MyRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MyRequest* New() const final {
    return CreateMaybeMessage<MyRequest>(NULL);
  }

  MyRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MyRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MyRequest& from);
  void MergeFrom(const MyRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MyRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // required int32 b = 2;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GrpcService.MyRequest)
 private:
  void set_has_a();
  void clear_has_a();
  void set_has_b();
  void clear_has_b();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MyResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GrpcService.MyResponse) */ {
 public:
  MyResponse();
  virtual ~MyResponse();

  MyResponse(const MyResponse& from);

  inline MyResponse& operator=(const MyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MyResponse(MyResponse&& from) noexcept
    : MyResponse() {
    *this = ::std::move(from);
  }

  inline MyResponse& operator=(MyResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MyResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MyResponse* internal_default_instance() {
    return reinterpret_cast<const MyResponse*>(
               &_MyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MyResponse* other);
  friend void swap(MyResponse& a, MyResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MyResponse* New() const final {
    return CreateMaybeMessage<MyResponse>(NULL);
  }

  MyResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MyResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MyResponse& from);
  void MergeFrom(const MyResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MyResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GrpcService.MyResponse)
 private:
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 result_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MyRequest

// required int32 a = 1;
inline bool MyRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MyRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MyRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MyRequest::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 MyRequest::a() const {
  // @@protoc_insertion_point(field_get:GrpcService.MyRequest.a)
  return a_;
}
inline void MyRequest::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:GrpcService.MyRequest.a)
}

// required int32 b = 2;
inline bool MyRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MyRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MyRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MyRequest::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 MyRequest::b() const {
  // @@protoc_insertion_point(field_get:GrpcService.MyRequest.b)
  return b_;
}
inline void MyRequest::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:GrpcService.MyRequest.b)
}

// -------------------------------------------------------------------

// MyResponse

// required int32 result = 1;
inline bool MyResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MyResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MyResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MyResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 MyResponse::result() const {
  // @@protoc_insertion_point(field_get:GrpcService.MyResponse.result)
  return result_;
}
inline void MyResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:GrpcService.MyResponse.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GrpcService

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_2eproto
